# base image
FROM python:3.7.0-alpine

# nuevo
# instalando dependencias
RUN apk update && \
    apk add --virtual build-deps gcc python-dev musl-dev && \
    apk add postgresql-dev && \
    apk add netcat-openbsd

# estableciendo directorio de trabajo
WORKDIR /usr/src/app

# agregando e instalando requierimientos
COPY ./requirements.txt /usr/src/app/requirements.txt
RUN pip install -r requirements.txt

# nuevo
# copiando entrypoint.sh
COPY ./entrypoint.sh /usr/src/app/entrypoint.sh
RUN chmod +x /usr/src/app/entrypoint.sh

# copiando app
COPY . /usr/src/app

# nuevo
# ejecutando servidor
CMD ["sh","-c","chmod 755 /usr/src/app/entrypoint.sh && /usr/src/app/entrypoint.sh"]